---
- name: Install httpd on the frontend server
  hosts: frontend
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
    - name: Install httpd server
      apt:
        name: apache2
        state: present
    - name: Start the httpd server
      service:
        name: apache2
        state: started
        enabled: yes

    - name: create index.html file
      copy:
        content: "Welcome to my web server"
        dest: /var/www/html/index.html
        mode: '0644'
